version: '3.2'

networks:
    etl_dev:
        external: true
        
services:
  https-portal:
        image:  steveltn/https-portal:1
        ports:
            - "80:80"
            - "443:443"
        restart: always
        environment:
            DOMAINS:  "localhost -> http://quantum_chat:8090"
            STAGE:  "production"
            FORCE_RENEW:  "false"
        networks:
            - bridged
        depends_on:
            - "chat-app"
  chat-app:
    container_name: quantum_chat
    build: .
    ports: 
      - "8090:8090"
  db:
    image: mysql:latest
    container_name: quantum_db
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=quantum123
    - MYSQL_DATABASE=quantum_chat
    volumes:
    - ./db_backup.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 20s
      retries: 20