version: '3'
services:
  chat-app:
    container_name: quantum_chat
    build: .
    ports: 
      - "8090:8090"
  db:
    image: mysql:latest
    container_name: quantum_db
    ports:
    - "3306:3306"
    volumes:
    - ./db_backup.sql:/docker-entrypoint-initdb.d/dump.sql
    environment::
    - MYSQL_ROOT_PASSWORD=quantum123
    - MYSQL_DATABASE=quantum_chat